mattermost/mattermost-plugin-zoom

webapp/components/channel_header_button/channel_header_button.jsx

https://mattermost.atlassian.net/browse/MM-10206

MM-10206 Remove call to removed function

---

webapp/src/client/client.js

Hope this is the correct fix. At least, it compiles :smile:

Make client route indipended from plugin id

---

server/zoom/client.go
webapp/src/actions/index.js

I failed to reproduce the failures in https://mattermost.atlassian.net/browse/MM-13814, so I improved the error messages in case it happens again.

MM-13814 - Improved the error messages for Zoom API failures

---

plugin.json
server/manifest.go
webapp/package.json
webapp/src/manifest.js

Bump to 1.0.4 to release some fixes

bump zoom to 1.0.4

---

go.mod
server/plugin.go
webapp/package-lock.json
webapp/src/actions/index.js

redoing #27 to a release branch

[MM-15960] Fixed 'no feedback on failed zoom icon click' (#27)

---

plugin.json
server/manifest.go
webapp/package.json
webapp/src/actions/index.js
webapp/src/manifest.js

- These are cherry picks from the 1.0.7 branch.

Merge 1.0.7 changes

---

plugin.json
server/manifest.go
webapp/src/manifest.js

@jwilander fixed the leftover test, but now need to bump the release again.

Bumped release version to 1.1.1

---

server/http.go
webapp/src/actions/index.js
webapp/src/client/client.js

This PR makes it so the Zoom meeting automatically opens, so the user that started the meeting does not have to click the `Start Meeting` button.
https://mattermost.atlassian.net/browse/MM-20071

[MM-20071] zoom will now automatically open upon clicking the zoom camera icon

---

server/command.go
server/configuration.go
server/utils.go

Validate the authentication configuration for zoom plugin
####
Fixes https://mattermost.atlassian.net/browse/MM-21291

validate the authentication configuration

---

server/command.go
server/http.go
webapp/src/components/post_type_zoom/index.js

This PR changes the post created by the zoom plugin to display the username that created the zoom meeting.
Resolves #48

Display username that created zoom meeting

---

server/command.go
server/http.go
server/plugin_test.go
server/zoom/webhook.go
webapp/src/actions/index.js
webapp/src/client/client.js
webapp/src/components/post_type_zoom/index.js
webapp/src/components/post_type_zoom/post_type_zoom.jsx

Avoid race condition with users rapid-firing invites
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/54

[GH-54] Avoid race condition with users rapid-firing invites

---

webapp/package-lock.json

Updated serialze-javascript
Steps used:
- git latest master
- make clean
- cd webapp
- npm audit fix

Update latest dependencies

---

webapp/src/components/post_type_zoom/post_type_zoom.jsx

MM-22921 - Updating zoom styling for attachment
https://mattermost.atlassian.net/browse/MM-22921

MM-22921 - Updating zoom styling for attachment

---

server/configuration.go

Update client OnConfigurationChange
Fixes #86

[GH-86] Update client OnConfigurationChange

---

webapp/src/actions/index.js
webapp/src/client/client.js
webapp/src/index.js

Fix errors occurring when using mattermost server on a subdir.
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/91
https://mattermost.atlassian.net/browse/MM-23411

[GH-91][MM-23411] Fix error when using mattermost server on a subdir

---

README.md

PR to add release version and Help Wanted Badges to the readme
Do Not Merge added until the following issue is resolved.
https://github.com/mattermost/mattermost-plugin-zoom/issues/117
n/a

add codecov, latest release and HW badges

---

server/command.go

Save state when using connect command on Account level oauth
None

Save state when using connect on Account level oauth

---

plugin.json

Drop Beta from OAuth option
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/201

Drop Beta from OAuth

---

docs/installation/zoom-configuration/README.md

Fixes a small typo in the documentation

Fixing typo in configuration/readme

---

server/http.go
webapp/src/components/post_type_zoom/post_type_zoom.jsx

I updated the "I have ended the meeting." phrasing to "The meeting has ended." as asked in #210.
https://github.com/mattermost/mattermost-plugin-zoom/issues/210

 Updated the "I have ended the meeting." phrasing to "The meeting has ended." as asked in #210

---

plugin.json

Remove "Mattermost 5.2+" from plugin description

---

CODEOWNERS
README.md

Change codeowners to mickmister and trilopin

---

plugin.json

https://community.mattermost.com/core/pl/qua38zmrnjrz3qj3zyc5gcuitw

Update docs link in plugin.json

---

server/webhook.go

Fixes: https://github.com/mattermost/mattermost-plugin-zoom/actions/runs/7259474627/job/19776688186?pr=324

[MM-42] Fix CI error: 'xyz' has 2 occurrences, make it a constant

---

README.md

Fix link to plugin docs in the readme

---

server/store.go
server/webhook.go
server/webhook_test.go

Update code to handle invalid log statement while receiving the meeting ended webhook
https://community.mattermost.com/core/pl/hh7p3s8nk7bnpe6bhpjkq7nbsw

Update code to handle invalid log statement while receiving the meeting ended webhook

---

server/http.go
server/telemetry.go

- Fixed issue of zoom settings command being ignored after connecting user
Fixes #345 
- Zoom Settings are being checked after connecting of the user
[screen-capture (9).webm](https://github.com/mattermost/mattermost-plugin-zoom/assets/100013900/c5f40e9f-92f4-478c-b279-17632de7464c)

Fix issue of zoom settings command being ignored after connecting user

---

.github/workflows/issue_add.yml

- Added workflow file to add new issues to github board
https://github.com/orgs/mattermost/projects/9/views/1

[MM-557] Added workflow file to add new issues to github board

---

README.md

Removed code maintainer, co-maintainer from the README

Removed code maintainer, co-maintainer from the README

---

server/http.go
server/plugin_test.go
server/store.go
server/webhook.go

Fixed the update of Slack attachment props for the meeting post
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/410

[MM-410]: Fixed the update of Slack attachment props for the meeting post

---

.github/workflows/ci.yml
webapp/package-lock.json
webapp/package.json
webapp/src/client/client.js

**Summary**
Upgrade mattermost-redux to 10.8.0

Upgrade mattermost-redux to 10.8.0
