plugin.json
webapp/components/icon.jsx
webapp/components/post_type_zoom/index.js
webapp/components/post_type_zoom/post_type_zoom.jsx
webapp/index.js
webapp/package-lock.json
webapp/package.json
webapp/webpack.config.js

See https://github.com/mattermost/mattermost-webapp/pull/1473.

switch to webpack externals

---

go.mod
server/plugin.go
webapp/package-lock.json
webapp/src/actions/index.js

- We were importing the local go package a little incorrectly, causing us to import our own package from github (instead of just using the files in the local tree). This meant that we were using version 1.0.3 of that 'package', while the rest of the plugin was currently at 1.0.6.
- Also, redux was changed a bit back in 2019-04-15 and the action we were using was out of date.
Error looks like this:
Fixes: [MM-15960](https://mattermost.atlassian.net/browse/MM-15960)

[MM-15960] Fixed 'no feedback on failed zoom icon click'

---

go.mod
go.sum
server/http.go
server/zoom/client.go
server/zoom/meeting.go
server/zoom/user.go
server/zoom/webhook.go

Follow up from https://github.com/mattermost/mattermost-plugin-zoom/pull/25

Refactor zoom package

---

go.mod
go.sum
server/command.go
server/plugin.go
server/plugin_test.go

Summary:
- Mobile app users does not have the zoom start button and would be great to have the option of the `/zoom start` command to start a zoom meeting.
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/31

Implemented '/zoom start' command as an alternative to the zoom button

---

server/http.go

Fix guard condition to only update meeting to Ended status when receiving a webhook event for `WebhookStatusEnded` status. This was causing the meeting post to update to ended when the meeting was started. This was regression caused by: https://github.com/mattermost/mattermost-plugin-zoom/pull/29
[MM-19716](https://mattermost.atlassian.net/browse/MM-19716)

MM-19716 - Fix guard condition to update meeting to Ended status

---

webapp/package-lock.json
webapp/package.json
webapp/src/actions/index.js
webapp/src/client/client.js
webapp/webpack.config.js

This PR upgrades mattermost-redux to use `Client4.getOptions`, in order to correctly include the csrf token.
https://mattermost.atlassian.net/browse/MM-18201
- Set `ServiceSettings.ExperimentalStrictCSRFEnforcement` to true in the server's config.json
- Verify that you can click the zoom button to begin a meeting

[MM-18201] Use mattermost-redux to handle csrf issues

---

server/http.go

The value for `meetingURL` was not set in this PR https://github.com/mattermost/mattermost-plugin-zoom/pull/53
https://mattermost.atlassian.net/browse/MM-21314

[MM-21314] Initialize meetingURL

---

webapp/src/components/icon.jsx

Added a 'Video Icon' aria-label to start zoom meeting button
Resolves #59

Add aria-label to start meeting button

---

server/command.go
server/http.go
webapp/src/components/post_type_zoom/index.js

Old zoom messages do not have the property "meeting_creator_username", and therefore show "undefined has started a meeting".
Also, the race condition confirmation also is lacking the "meeting_creator_username" property, so this PR adds that.
https://mattermost.atlassian.net/browse/MM-22638
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/76

[MM-22638] Fix undefined name

---

server/command.go
server/http.go
webapp/src/components/post_type_zoom/index.js
webapp/src/components/post_type_zoom/post_type_zoom.jsx

Meeting messages do not trigger notifications on direct channels due to them being posted by a bot, and not by any of the two users in the channel. Also, since they are posted by a bot, the user that created the meeting cannot delete the post.
This PR solves both problems by posting the messages in the name of the user, instead of posting them as the bot.
Fix https://mattermost.atlassian.net/browse/MM-23173
Fix https://mattermost.atlassian.net/browse/MM-19931

Use user ID instead of bot ID to post meetings

---

server/http.go

The message shown when you don't have the plugin or you are in mobile is way
worse than the one with the plugin. This change fill a bit the gap using an
slack attachment that is more similar to the custom post format.

Adding slack attachment on messages without plugin (and mobile)

---

server/command.go

Remove Disconnect command when using JWT, so JWT users do not see commands they cannot use.
#127

[GH-127] Remove Disconnect command when using JWT

---

server/http.go

Post the already created authmessage on failed connection when using the header icon
Fix #137

[GH-137] Fix "If user's email is not valid for JWT Zoom, launching Zoom from the icon will show oAuth link "

---

server/command.go
server/http.go
server/plugin.go
server/plugin_test.go
webapp/.npmrc

In order to allow the meeting ended webhook, we have to store the meeting Post ID in the KVStore to modify it after the call. This was not done when creating a meeting via slash command.
I also added the expiry time to the post IDs so they do not create garbage if the webhook never arrives (for example because the meeting never started).
Fix #128

 Store post ID when creating meeting via slash command, add some logging and set expiry time to meeting post IDs to avoid garbage in the KVStore

---

server/command.go
server/store.go

Add friendly message on disconnect if user is not currently authenticated
https://github.com/mattermost/mattermost-plugin-zoom/issues/178

solves GH 178 - Add friendly message on disconnect if user is not currently authenticated

---

.gitignore
server/plugin.go

Apparently due to recent changes in how Zoom handles OAuth applications it no longer accepts specifying scopes with OAuth calls. According to Zoom, scopes passed in URLs were never used but now are no longer accepted.
Here's forum discussion around the topic: https://devforum.zoom.us/t/invalid-scope-errors/52654
From Zoom's employee response:
> "While Zoom never explicitly supported including app scopes as part of the authorization URL, this was previously ignored in the case that they were included. However, as part of our ongoing commitment of prioritizing security, a recent enhancement was made that will now consider scopes added directly to the authorization URL to be considered invalid. You will need to omit the scope parameter from your URL and let your OAuth Marketplace App handle …

Remove scopes from OAuth calls

---

server/http.go
server/plugin_test.go

Prevent user post zoom call if channel permissions make member with read-only permissions
https://github.com/mattermost/mattermost-plugin-zoom/issues/223

[MM-223] Fixing Post Permissions Access

---

server/http.go
server/plugin_test.go

Zoom sends webhooks for various reasons. The Mattermost Zoom Plugin only handles `meeting.ended` events. For all others, a `501 - Not Implemented` status code is returned. [Zoom expects a 200 or 204 response](https://marketplace.zoom.us/docs/api-reference/webhook-reference/#notification-delivery), otherwise it assumes the delivery failed and it will try again at a future time. This means that by returning a 501, Zoom will re-queue the webhook to be sent again - exasperating the issue. 
[This](https://community-daily.mattermost.com/private-core/pl/46u9c9hf7fgfjxbubtiet65iao) [has](https://community-daily.mattermost.com/private-core/pl/tsqdihdh5iyr7m1na3fuw97uge) [been](https://community-daily.mattermost.com/private-core/pl/m75q1yztjpyu9d13bkd4j9ofuy) causing us to go over alert thresholds …

Make unhandled webhook events return 200 instead of 501

---

server/plugin.go
server/zoom/client.go
server/zoom/oauth.go

This reverts commit 8a5a54dcb4b1970d8c70a618eaa983a29c9c8402.
This PR reverts https://github.com/mattermost/mattermost-plugin-zoom/pull/242, which introduced some issues with OAuth token management, including an error with coordinating encryption/decryption, resulting in corrupted tokens.

Revert "[GH-235] Refresh token on user level oauth (#235) (#242)"

---

server/plugin.go

Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/276

Check nil license features

---

server/telemetry.go

Previously errors returned from the telemetry tracker didn't get logged. This PR adds proper log messages for all errors the telemetry tracker returns.
https://mattermost.atlassian.net/browse/MM-51269

[MM-51269] Log errors from telemetry events

---

README.md

Removed mention of JWT setup from the README as it is no longer supported
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/309

[GH-309]: Removed mention of JWT setup from the README as it is no longer supported.

---

server/command.go

Removed the unnecessary hint in "settings" command.
Earlier:
Now:
- "[command]" should not be visible in the "settings" slash command suggestion.
- Type the command `/zoom settings`.
MM version: v7.8.10
Node version: 14.18.0
Go version: 1.19.0
Fixes #312

[GH-312] Removed the unnecessary hint in "settings" command.

---

server/http.go
webapp/src/actions/index.js
webapp/src/client/client.js
webapp/src/components/post_type_zoom/post_type_zoom.jsx

Fix the following issues:
- Not able to create a meeting in the threads view.
- Not able to create a meeting by clicking "Create New Meeting" in a channel.
- Able to create a meeting in the threads view
- Able to create a new meeting by clicking the "Create New Meeting" button
- For threads view:
1. Have CRT enabled, and open the Threads view
2. Open a thread that pops into the RHS
3. Click the Zoom button on the right
- For clicking the button:
1. Start a new meeting from the desired user's account.
2. Without ending the meeting started, try to start a new meeting again.
3. Click on the "Create New Meeting" button.
- The meetings should be created successfully.
MM version: v7.8.10
Node version: 14.18.0
Go version: 1.19.0
FIxes #311

[GH-311] Fix issues: Not able to create meeting in threads view and by clicking "Create New Metting" button in a channel

---

webapp/src/client/client.js

- When a new meeting is started using the Zoom icon in the app bar/channel header the user is not getting redirected to the meeting tab because the meeting URL is undefined.
- We updated the logic to convert the response of the start meeting API to JSON for fetching the meeting URL.
- When a user starts a new meeting using the Zoom icon in the app bar/channel header, he/she should be redirected to the meeting page.
- Click on the Zoom icon in the app bar/channel header. (Note: These should not be an existing meeting of the user in that channel)
MM version: v7.8.10
Node version: 14.18.0
Go version: 1.19.0
Fixes #313

[GH-313] Redirect user when a new meeting is started

---

plugin.json

Replaced absolute GitHub link with permalink [via Marketing](https://docs.google.com/spreadsheets/d/1O601H_A0IM8pR3FOfue29_C8flGV7xK3ts-tJUVDHHg/edit#gid=0).
Addresses: https://mattermost.atlassian.net/browse/MM-55436

Replaced legacy GitBook URLs with PL link

---

README.md
plugin.json

1. Added the latest screenshot.
2. Completed the documentation for plugin configuration.
Fixes #167 
Fixes #215

[GH-167][GH-215] Removed "Beta" label on Account-Level app, and updated documentation

---

README.md

Updated the first image on the README page to be an absolute link rather than a hashed image. Looking to verify whether GitHub converts the path to a hashed image post-commit.

Test PR: Image link path

---

webapp/src/components/post_type_zoom/post_type_zoom.jsx

Fix issue: Emoji not working in meeting title
Fixes https://github.com/mattermost/mattermost-plugin-zoom/pull/322#issuecomment-1893243798

[MM-134] Fix issue: Emoji not working in meeting title

---

server/command.go
server/http.go

- Updated the default setting for meeting ID
- Updated the message on "ask meeting type" slack attachment.
- When a user creates a Zoom meeting, he should get an attachment to select the meeting type for that meeting.
Note: Make sure that the user has not set their meeting preference with the `/zoom settings` command.
Fixes https://community.mattermost.com/core/pl/nc17jfy4zi85jcq7dw57j1trwy

[MM-154] Updated the default setting for meeting ID

---

Makefile

- Add "CGO_ENABLED=0" flag in build command
Fixes #347

[GH-347] Fix issue: Release v1.7.0 not working on older version of MM cloud servers

---

webapp/src/components/post_type_zoom/post_type_zoom.jsx

- Fixed the issue of user not able to navigate post button when given option to `Create New Meeting` or `Join Existing Meeting`
#68

[MM-329] Fix issue of not able to access post button while navigating using tab

---

server/command.go

- Fixed issue of settings command working for non-connected users
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/346
- Test the `/zoom settings` command should not work for non-connected users.

Fix issue of settings command working for non-connected users

---

plugin.json

Upgraded the `min_server_version` for zoom plugin to 8.1.0 from 5.37.0
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/392

[MM-546]: Upgraded the min_server_version to 8.1.0 from 5.37.0

---

server/command.go
server/http.go
server/plugin_test.go
server/store.go

- Added logic to use KV store for storing user preferences instead of the preference table
- Added logic to delete preference from preference table after storing it in the kv store for existing users
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/340
- Install any existing Zoom release and configure the plugin and select any preference for a user.
- Configure the plugin with this PR's build and check if the setting remains the same and the user is able to create the meeting with the selected preference.

[MM-570] Use KV store to store user preference

---

server/http.go

The Zoom plugin had an issue where if a meeting link was posted in a channel within the last 30 seconds, the Zoom plugin would send a reminder post that a meeting link had been posted in the channel, regardless of whether the meeting had ended or not. This PR fixes the issue of reminder posts being sent even though the meeting has ended.
**Requisite**: The webhook needs to be set up and working properly.
Fixes #373 
-Set up the Zoom plugin and the webhook.
- Start a meeting and end it instantly.
- Create a new meeting within 30 seconds.
- The Zoom plugin posts a reminder that a meeting link has already been posted in the channel in the last 30 seconds.
- A new meeting link is posted if all meetings from the last 30 seconds have ended.

[GH-373]: Fixed the issue of zoom plugin sending confirmation although meeting started in last 30 seconds have ended

---

.github/workflows/ci.yml

Fix CI pipeline by adding permissions for id-token to write
https://mattermost.atlassian.net/browse/CLD-9264
From: https://github.com/mattermost/mattermost-plugin-starter-template/pull/223

fix: add missing id-token to write to CI pipeline
